### ISSUE TITLE
Koa 2+ with async/await now throwing warning

### ISSUE THREAD

**Issue by damianobarbati** [vgno/koa-remove-trailing-slashes#1]
I've been using this package for long, thanks for it! 

Could you please upgrade it for current koa which uses async/await (Node 7.8+)?

"koa": "^2.2.0",
"koa-remove-trailing-slashes": "^1.0.0",

Throws:
```koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at server.js:15:5```

**Comment by dlmr** [comment]
So sorry for missing this issue completely. Thanks for reporting it!

Maybe you have found another package at this point but will update it soon, sorry again for the delay!

**Comment by damianobarbati** [comment]
Don't worry @dlmr, I then found `koa-no-trailing-slash` :)

Thanks and keep up the good work!

**Comment by dlmr** [comment]
Closed through #2 and released in `2.0.0`.
